/* Shared data for Learn page + article view */
window.ARTICLES = [
  {
    id: "story-of-recovery",
    featured: true,
    tag: "RECOVERY",
    tagClass: "recovery",
    title: "The story of recovery",
    excerpt: "What recovery actually means, why it matters more than you think, and how Morpheus turns the balance between stress and recovery into a single number you can act on.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "7 min",
    image: "https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?w=1400&auto=format&fit=crop",
  },
  {
    id: "hrv-guide",
    tag: "HRV",
    tagClass: "hrv",
    title: "Everything you need to know about HRV",
    excerpt: "Over the last few years, heart rate variability, or HRV, has become a widely used metric across a variety of fitness apps.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "6 min",
    image: "https://www.figma.com/api/mcp/asset/e69a16f0-be10-46bd-a09c-b08d84c02895",
  },
  {
    id: "recovery-workouts",
    tag: "TRAINING",
    tagClass: "training",
    title: "Why you need Recovery workouts",
    excerpt: "There are many ways to try and speed up recovery these days, from massage and soft tissue work, to hydrotherapy, meditation, and more.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "6 min",
    image: "https://www.figma.com/api/mcp/asset/0472026e-d7de-49cc-9668-97d6898d38bb",
  },
  {
    id: "sleep-recovery",
    tag: "SLEEP",
    tagClass: "sleep",
    title: "How does sleep impact recovery?",
    excerpt: "These days, it's no secret that sleep is important for almost every area of health, fitness, and performance.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "6 min",
    image: "https://www.figma.com/api/mcp/asset/679ca6c5-4b15-4f57-a684-221f683b2778",
  },
  {
    id: "ten-thousand-steps",
    tag: "STEPS",
    tagClass: "steps",
    title: "Do you really need 10,000 steps?",
    excerpt: "With the popularity of Fitbit and other step trackers, you could probably ask any grade-school kid how many steps people should get each day.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "6 min",
    image: "https://www.figma.com/api/mcp/asset/abf94476-a1d8-42e3-9319-366d3504171d",
  },
  /* ── Recent articles (Figma node 2626-5806) ── */
  {
    id: "building-recovery-roadmap",
    tag: "TRAINING",
    tagClass: "training",
    title: "Building your recovery roadmap",
    excerpt: "You've put in a lot of work to get here—well done! Let's quickly review what you've learned on this 30-day journey.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "10 min",
    image: "https://www.figma.com/api/mcp/asset/a8a17495-0db2-49b8-99f6-68af0630d4ea",
  },
  {
    id: "zone-interval-training",
    tag: "ZBIT",
    tagClass: "zbit",
    title: "Zone-based interval training",
    excerpt: "One of the most important and unique features in Morpheus is also its newest: zone-based intervals.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "7 min",
    image: "https://www.figma.com/api/mcp/asset/198205b1-74e9-4e75-a172-a3df384e606e",
  },
  {
    id: "weekly-training-plan",
    tag: "TRAINING",
    tagClass: "training",
    title: "Building a weekly training plan",
    excerpt: "When people start a new training program or diet, they typically make quick progress. Their strength goes up, the weight on the scale goes down.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "8 min",
    image: "https://www.figma.com/api/mcp/asset/c01d094c-76b1-4088-9740-b2b4c4fd092a",
  },
  {
    id: "morpheus-hr-zones",
    tag: "Heart rate zones",
    tagClass: "hr-zones",
    title: "Morpheus heart rate zones",
    excerpt: "One of the most important things Morpheus enables you to do is train in heart zones based on your recovery each day.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "6 min",
    image: "https://www.figma.com/api/mcp/asset/7d326984-1617-4a62-a372-8056d767f011",
  },
  {
    id: "dynamic-hr-training",
    tag: "Heart rate zones",
    tagClass: "hr-zones",
    title: "Morpheus heart rate zones",
    excerpt: "One of the most important things Morpheus enables you to do is train in heart zones based on your recovery each day. The three Morpheus zones are based on a concept called dynamic heart rate training.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "6 min",
    image: "https://www.figma.com/api/mcp/asset/7d326984-1617-4a62-a372-8056d767f011",
  },
  {
    id: "intro-hrv",
    tag: "HRV",
    tagClass: "hrv",
    title: "Intro to Heart Rate Variability",
    excerpt: "Over the last few years, heart rate variability, or HRV, has become a widely used metric across a variety of fitness apps. It's also at the heart of how Morpheus calculates your recovery score.",
    author: "Joel Jamieson",
    authorHandle: "Founder of Morpheus",
    avatar: "https://www.figma.com/api/mcp/asset/30413949-2a96-40da-b68f-36266fce8359",
    date: "April 12, 2026",
    readTime: "7 min",
    image: "https://www.figma.com/api/mcp/asset/ca579bfd-d01c-4c8c-a48c-80ba2b5da4bd",
  },
  /* ── Archive articles ── */
  {
    id: "caffeine-timing",
    tag: "NUTRITION",
    tagClass: "nutrition",
    title: "The caffeine half-life trap: why your 2 PM coffee is ruining Wednesday",
    excerpt: "Caffeine's quarter-life is longer than you think. Timing the cutoff is the easiest sleep intervention there is.",
    author: "Emily Chen, RD",
    authorHandle: "Performance Nutrition",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&auto=format&fit=crop",
    date: "April 2, 2026",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop",
  },
  {
    id: "strength-longevity",
    tag: "TRAINING",
    tagClass: "training",
    title: "Strength is the longevity lever nobody wants to pull",
    excerpt: "Grip strength predicts all-cause mortality better than blood pressure. Here's how to train it without a garage gym.",
    author: "Dr. Stuart Phillips",
    authorHandle: "Muscle Physiology",
    avatar: "https://images.unsplash.com/photo-1548372290-8d01b6c8e78c?w=200&auto=format&fit=crop",
    date: "March 28, 2026",
    readTime: "10 min",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&auto=format&fit=crop",
  },
  {
    id: "cold-exposure",
    tag: "RECOVERY",
    tagClass: "recovery",
    title: "Cold exposure after lifting: helpful habit or hypertrophy saboteur?",
    excerpt: "The plunge feels elite. The literature is less generous. When to ice, and when to leave the inflammation alone.",
    author: "Dr. Andrew Huberman",
    authorHandle: "Neuroscience",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop",
    date: "March 24, 2026",
    readTime: "7 min",
    image: "https://images.unsplash.com/photo-1551847812-f815b31ac2cb?w=1200&auto=format&fit=crop",
  },
  {
    id: "vo2-max",
    tag: "TRAINING",
    tagClass: "training",
    title: "VO₂ max is a proxy, not a destination — stop chasing the number",
    excerpt: "The top of your aerobic ceiling is a lagging indicator of everything you already did right. Train the inputs.",
    author: "Alex Hutchinson",
    authorHandle: "Endurance Science",
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&auto=format&fit=crop",
    date: "March 22, 2026",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=1200&auto=format&fit=crop",
  },
  {
    id: "resting-hr-trend",
    tag: "RECOVERY",
    tagClass: "recovery",
    title: "Your resting heart rate trend is more useful than today's number",
    excerpt: "A single morning reading is noisy. A 14-day rolling average tells you whether your training load is landing.",
    author: "Dr. Kelly Starrett",
    authorHandle: "Movement Coach",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop",
    date: "March 20, 2026",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=1200&auto=format&fit=crop",
  },
  {
    id: "mental-load",
    tag: "MINDSET",
    tagClass: "mindset",
    title: "Why mental stress and physical load share the same recovery bucket",
    excerpt: "Cortisol doesn't care whether the stressor was a deadline or a deadlift. Budget accordingly.",
    author: "Dr. Lisa Feldman",
    authorHandle: "Performance Psychology",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop",
    date: "March 18, 2026",
    readTime: "7 min",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&auto=format&fit=crop",
  },
  {
    id: "protein-timing",
    tag: "NUTRITION",
    tagClass: "nutrition",
    title: "The protein timing question: does the anabolic window actually exist?",
    excerpt: "Two decades of research have gradually widened the window from 30 minutes to about a day. What that means for you.",
    author: "Dr. Brad Schoenfeld",
    authorHandle: "Hypertrophy Research",
    avatar: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?w=200&auto=format&fit=crop",
    date: "March 16, 2026",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200&auto=format&fit=crop",
  },
  {
    id: "deload-guide",
    tag: "TRAINING",
    tagClass: "training",
    title: "The honest deload: planning weeks off so you actually come back stronger",
    excerpt: "Most deloads fail because they aren't deloads at all. A framework that works even if you hate easy weeks.",
    author: "Greg Nuckols",
    authorHandle: "Strength Science",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop",
    date: "March 14, 2026",
    readTime: "9 min",
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=1200&auto=format&fit=crop",
  },
];

window.CATEGORIES = [
  { key: "all",      label: "All"      },
  { key: "hrv",      label: "HRV"      },
  { key: "training", label: "Training" },
  { key: "recovery", label: "Recovery" },
  { key: "sleep",    label: "Sleep"    },
  { key: "steps",    label: "Steps"    },
  { key: "nutrition", label: "Nutrition" },
];
